### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by ChuckDorval** [RTXI/plugin-template#2]
Under 'Making New Module' , step #3 Modify files, instructions should read:

$ sed -i 's/plugin-template/<new-name-here>/g' plugin-template.* Makefile
$ sed -i 's/plugin_template/<new_name_here>/g' plugin-template.* Makefile
$ sed -i 's/PluginTemplate/<NewNameHere>/g' plugin-template.* Makefile

**Comment by anselg** [comment]
You're right. The `sed` scripts on the website won't replace the name of the binary the Makefile produces. Thanks for pointing this out.

**Comment by anselg** [comment]
The website has been updated with new instructions. 
http://rtxi.org/docs/tutorials/2015/04/10/making-new-rtxi-modules/
